In [1]:
import torch

In [7]:
a = torch.load('models/nin_halfadd.pth.tar')

In [8]:
conv1 = a['state_dict']['conv1.weight']
conv2 = a['state_dict']['conv1_1.weight']

In [10]:
def compare_float(mat1, mat2, rDelt=0.01, aDelt=None):
    if aDelt != None:
        res = (abs(mat1 - mat2) < aDelt)
    else:
        res = (((2*abs(mat1 - mat2))/(abs(mat1 + mat2))) < rDelt)
    return res
    
print (float(compare_float(conv1, conv2, rDelt = 0.00001).sum())/float(conv1.view(-1).size()[0]))

0.9725


In [1]:
print(range(3))

[0, 1, 2]


In [2]:
from models import nin_crazy
from models import nin_halfadd

In [3]:
model = nin_crazy.Net()
model2 = nin_halfadd.Net()
para2_file = torch.load("models/nin_crazy.ONE.pth.tar")
para2 = para2_file['state_dict']

In [8]:
def load_pretrained(model, filePath, same):
    pretrained_model = torch.load(filePath)
    useState_dict = model.state_dict()
    preState_dict = pretrained_model['state_dict']
    best_acc = pretrained_model['best_acc']

    if same:
        useState_dict = preState_dict
    else:
        useKeys = useState_dict.keys()
        preKeys = preState_dict.keys()
        j = 0
        for key in useKeys:

            if j == 59:
                j = 0
            useState_dict[key].data = preState_dict[preKeys[j]].data
            j +=1
    model.load_state_dict(useState_dict)
    return model

In [9]:
elsemodel = load_pretrained(model = model2, filePath = "models/nin_crazy.2d.pth.tar", same = False)

In [17]:
def ExBitInverse(x):
    Expo = (x.log2().floor())
    num = x * pow(2,2 * (-Expo))
    return num

In [28]:
for _ in range(10):
    a = torch.randint(0,20,[1]).to(torch.float32)
    #a = torch.Tensor([8])
    num = ExBitInverse(a) 
    print(a, num.item())

(tensor([19.]), 0.07421875)
(tensor([9.]), 0.140625)
(tensor([14.]), 0.21875)
(tensor([0.]), nan)
(tensor([19.]), 0.07421875)
(tensor([5.]), 0.3125)
(tensor([4.]), 0.25)
(tensor([9.]), 0.140625)
(tensor([5.]), 0.3125)
(tensor([0.]), nan)


In [7]:
b = torch.randn([3,4,5,6])
mean = 10
std = 1000
size = b[0,0,:,:].size()
a = torch.normal(mean = mean * torch.ones(size), std = std)
print(a)

tensor([[  364.2174,  1077.2487, -1976.3032,   823.4763,   -17.1071,   155.8600],
        [  167.6001, -2167.5969,  1640.8624,  1372.7747,   363.8687, -1409.4314],
        [ -364.8358,   792.5723,  1474.2889,  -392.2496,  1006.5197, -1154.2645],
        [ -803.0588,  1037.0364,  1062.8910, -1036.6257,   183.8918,   635.3771],
        [  -58.4625, -1998.2662,    13.5549,   706.7608,  -376.5291,  -661.2606]])
